name: Publish SAM to AWS

on:
  push:
    branches: [ dev ]
    
jobs:
  sam-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: sam-deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
        run: |
          sam build --template-file=template.yaml --output-template-file packaged.yaml
          sam deploy --template-file packaged.yaml --capabilities CAPABILITY_IAM
